### ISSUE TITLE
bugs of documents

### ISSUE THREAD

**Issue by jhdxr** [SocialiteProviders/Weixin-Web#1]
It seems there is some wrong with the docs(  http://socialiteproviders.github.io/providers/weixin-web/)
for example
```
// This assumes that you have composer installed globally
composer require
```

```
return Socialite::with('')->redirect();
```

**Comment by DraperStudio** [comment]
Pushed a fix to the documenation https://github.com/SocialiteProviders/socialiteproviders.github.io/commit/1ca9a82d2b87e3eea44247d827b0f538ba76d5bf but the updated page doesn't seem to be rendered yet.

**Comment by jhdxr** [comment]
http://socialiteproviders.github.io/providers/weixin-web/ is updated, however it seems there is still some problem.
step 4 says
```
'weixin web' => [
    'client_id' => env('WEIXIN WEB_KEY'),
    'client_secret' => env('WEIXIN WEB_SECRET'),
    'redirect' => env('WEIXIN WEB_REDIRECT_URI'),  
],
```
but there should not have blank in the key of config file, and the .env file as well

**Comment by DraperStudio** [comment]
Should be updated.
