### ISSUE TITLE
ErrorException in Provider.php line 97: Undefined index: openid

### ISSUE THREAD

**Issue by OranTing** [SocialiteProviders/Weixin-Web#4]
ErrorException in Provider.php line 97:
Undefined index: openid
![snip20160623_1](https://cloud.githubusercontent.com/assets/13476576/16290984/9c4b67a6-3934-11e6-9de7-795d4f109be9.png)

@apollopy @AndyWendt

**Comment by apollopy** [comment]
Sorry since recently I am quite busy I don't have time to check it now.  

For now pls set 'composer.json' to be :

```json
        "laravel/socialite": "2.0.15",
        "socialiteproviders/manager": "2.1.1",
        "socialiteproviders/weixin-web": "2.0.1",
        "socialiteproviders/weixin": "2.0.1",
```

I will check it when I am free.

**Comment by OranTing** [comment]
好的。我试试上面的配置的版本看看。

**Comment by OranTing** [comment]
测试完毕了。我需要使用QQ 微博 微信 三个接口。
如果使用 "socialiteproviders/manager"  2.1.3之后的版本，那么weixin-web就会出错。
如果使用 "socialiteproviders/manager"  2.1.3之前的版本，那么QQ就只能使用2.0.3之前的版本。
经过多次测试，最终的版本如下：
"socialiteproviders/manager": "2.1.2",
"socialiteproviders/weibo": "^2.0",
 "socialiteproviders/qq": "2.0.3",
 "socialiteproviders/weixin-web": "^2.0",
 "socialiteproviders/weixin": "^2.0",
这样的话，微博、QQ、微信都测试没有问题了。看来这个版本也不是越新越好，需要多次测试。

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/Weixin-Web/commit/48b37624c3befc376eec4116cd73486f3ccc29e3

**Comment by gsion** [comment]
ErrorException in Provider.php line 97:
Undefined index: openid

解决方案，目前是 

原：
` $this->credentialsResponseBody = json_decode($response->getBody(), true);
`

改成
` $this->credentialsResponseBody = json_decode((string)$response->getBody(), true);
`
